### ISSUE TITLE
(Feedback) Star System Prototype

### ISSUE THREAD

**Issue by Trazel-Apeally** [DanielHamar/DAB_Advanced_JAVA#4]
Finished a basic version of the star class that can be reworked easily depending on the way we want it to work. I also uploaded the same version into a new folder titled "Star System Versions" on the OneDrive.

Please provide feedback if you have any qualms about the code.

[Star Class v0.01.zip](https://github.com/chiefhamar/DAB_Advanced_JAVA/files/1117591/Star.Class.v0.01.zip)

**Comment by chiefhamar** [comment]
Cool, I took a look and it looks like a good start.  You are miles ahead of me.  I've been tripping all over the place trying to get the multiple-choice thing working.  I finally have it working and now I'm hitting stumbling blocks with simple things like how to make none of the radio blocks checked when the form is brought up...It seems simple but it's frustrating.  I decided I'm going to crash course through all GUI stuff again tomorrow and try to catch up.

Feedback - Not sure that the program needs to have tallyStarPieces() actually say anything to the user.  It should tally in the background...but I'm sure you already thought of that.  Sorry, I can't get my head out of my own stuff.  I'll look at your code again tomorrow and see if anything else jumps out at me.  Good job.

**Comment by Trazel-Apeally** [comment]
The messages for now are purely for testing and can be removed/commented out in later versions.

As far as my other half of work goes, I'm going to wait until I have the graphical 'interface' of the Star System done before working on any the home overview screen. Since it'll be easier to work with than around it later on.

(Leaving ticket open for Anthony's feedback)
